[package]
name = "assembler"
version = "0.1.0"
edition = "2024"

[dependencies]
isa={ path = "../isa"}
shared={path = "../shared"}
thiserror = "2.0.11"
logos = "0.15.0"
bitflags = "2.9.0"
bumpalo = {version = "3.17.0", features = ["collections"]}
rustc-hash = "2.1.1"
slab = "0.4.9"
